### ISSUE TITLE
Add copyright to all programs

### ISSUE THREAD

**Issue by TheOneHyer** [Brazelton-Lab/lab_scripts#2]
Only about 1/3 of all programs in this repo are properly copyrighted. All scripts in this repo need the following copyright at the bottom of their docstrings (items in angled brackets must be replaced with appropriate information):

>     Copyright:
>
>         <program name>  <one-line program description>
>
>         Copyright (C) 2016  William Brazelton <comma-separated list of authors>
>
>         This program is free software: you can redistribute it and/or modify
>         it under the terms of the GNU General Public License as published by
>         the Free Software Foundation, either version 3 of the License, or
>         (at your option) any later version.
>
>         This program is distributed in the hope that it will be useful,
>         but WITHOUT ANY WARRANTY; without even the implied warranty of
>         MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>         GNU General Public License for more details.
>
>         You should have received a copy of the GNU General Public License
>         along with this program.  If not, see <http://www.gnu.org/licenses/>.

**Comment by cliqueNick** [comment]
Added copyright info to all the python scripts
